
package wsdl.UsuarioWsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UsuarioService", targetNamespace = "http://services.soap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UsuarioService {


    /**
     * 
     * @param id
     * @return
     *     returns wsdl.UsuarioWsdl.Usuario
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://services.soap.com/", className = "wsdl.UsuarioWsdl.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://services.soap.com/", className = "wsdl.UsuarioWsdl.FindByIdResponse")
    public Usuario findById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://services.soap.com/", className = "wsdl.UsuarioWsdl.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://services.soap.com/", className = "wsdl.UsuarioWsdl.DeleteResponse")
    public String delete(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @return
     *     returns java.util.List<wsdl.UsuarioWsdl.Usuario>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://services.soap.com/", className = "wsdl.UsuarioWsdl.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://services.soap.com/", className = "wsdl.UsuarioWsdl.FindAllResponse")
    public List<Usuario> findAll();

    /**
     * 
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://services.soap.com/", className = "wsdl.UsuarioWsdl.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://services.soap.com/", className = "wsdl.UsuarioWsdl.CreateResponse")
    public String create(
        @WebParam(name = "usuario", targetNamespace = "")
        Usuario usuario);

    /**
     * 
     * @param usuario
     * @return
     *     returns wsdl.UsuarioWsdl.Usuario
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://services.soap.com/", className = "wsdl.UsuarioWsdl.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://services.soap.com/", className = "wsdl.UsuarioWsdl.UpdateResponse")
    public Usuario update(
        @WebParam(name = "usuario", targetNamespace = "")
        Usuario usuario);

}
