
package EnvioWsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EnvioService", targetNamespace = "http://services.soap.com/", wsdlLocation = "http://localhost:8080/CorreoSoapServer-0.0.1/EnvioService?wsdl")
public class EnvioService_Service
    extends Service
{

    private final static URL ENVIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENVIOSERVICE_EXCEPTION;
    private final static QName ENVIOSERVICE_QNAME = new QName("http://services.soap.com/", "EnvioService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/CorreoSoapServer-0.0.1/EnvioService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENVIOSERVICE_WSDL_LOCATION = url;
        ENVIOSERVICE_EXCEPTION = e;
    }

    public EnvioService_Service() {
        super(__getWsdlLocation(), ENVIOSERVICE_QNAME);
    }

    public EnvioService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENVIOSERVICE_QNAME, features);
    }

    public EnvioService_Service(URL wsdlLocation) {
        super(wsdlLocation, ENVIOSERVICE_QNAME);
    }

    public EnvioService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENVIOSERVICE_QNAME, features);
    }

    public EnvioService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnvioService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EnvioService
     */
    @WebEndpoint(name = "EnvioServicePort")
    public EnvioService getEnvioServicePort() {
        return super.getPort(new QName("http://services.soap.com/", "EnvioServicePort"), EnvioService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnvioService
     */
    @WebEndpoint(name = "EnvioServicePort")
    public EnvioService getEnvioServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.soap.com/", "EnvioServicePort"), EnvioService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENVIOSERVICE_EXCEPTION!= null) {
            throw ENVIOSERVICE_EXCEPTION;
        }
        return ENVIOSERVICE_WSDL_LOCATION;
    }

}
