
package wsdlBanca.MedioDePagoWsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MedioDePagoService", targetNamespace = "http://services.soap.com/", wsdlLocation = "http://localhost:8080/BancaSoap/ws/MedioDePagoService?wsdl")
public class MedioDePagoService_Service
    extends Service
{

    private final static URL MEDIODEPAGOSERVICE_WSDL_LOCATION;
    private final static WebServiceException MEDIODEPAGOSERVICE_EXCEPTION;
    private final static QName MEDIODEPAGOSERVICE_QNAME = new QName("http://services.soap.com/", "MedioDePagoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/BancaSoap/ws/MedioDePagoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEDIODEPAGOSERVICE_WSDL_LOCATION = url;
        MEDIODEPAGOSERVICE_EXCEPTION = e;
    }

    public MedioDePagoService_Service() {
        super(__getWsdlLocation(), MEDIODEPAGOSERVICE_QNAME);
    }

    public MedioDePagoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEDIODEPAGOSERVICE_QNAME, features);
    }

    public MedioDePagoService_Service(URL wsdlLocation) {
        super(wsdlLocation, MEDIODEPAGOSERVICE_QNAME);
    }

    public MedioDePagoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEDIODEPAGOSERVICE_QNAME, features);
    }

    public MedioDePagoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MedioDePagoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MedioDePagoService
     */
    @WebEndpoint(name = "MedioDePagoServicePort")
    public MedioDePagoService getMedioDePagoServicePort() {
        return super.getPort(new QName("http://services.soap.com/", "MedioDePagoServicePort"), MedioDePagoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MedioDePagoService
     */
    @WebEndpoint(name = "MedioDePagoServicePort")
    public MedioDePagoService getMedioDePagoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.soap.com/", "MedioDePagoServicePort"), MedioDePagoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEDIODEPAGOSERVICE_EXCEPTION!= null) {
            throw MEDIODEPAGOSERVICE_EXCEPTION;
        }
        return MEDIODEPAGOSERVICE_WSDL_LOCATION;
    }

}
