
package wsdlBanca.MedioDePagoWsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MedioDePagoService", targetNamespace = "http://services.soap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MedioDePagoService {


    /**
     * 
     * @param medioDePago
     * @return
     *     returns wsdlBanca.MedioDePagoWsdl.CuentaBancaria
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://services.soap.com/", className = "wsdlBanca.MedioDePagoWsdl.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://services.soap.com/", className = "wsdlBanca.MedioDePagoWsdl.UpdateResponse")
    @Action(input = "http://services.soap.com/MedioDePagoService/updateRequest", output = "http://services.soap.com/MedioDePagoService/updateResponse")
    public CuentaBancaria update(
        @WebParam(name = "medioDePago", targetNamespace = "")
        MedioDePago medioDePago);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://services.soap.com/", className = "wsdlBanca.MedioDePagoWsdl.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://services.soap.com/", className = "wsdlBanca.MedioDePagoWsdl.DeleteResponse")
    @Action(input = "http://services.soap.com/MedioDePagoService/deleteRequest", output = "http://services.soap.com/MedioDePagoService/deleteResponse")
    public String delete(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param medioDePago
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://services.soap.com/", className = "wsdlBanca.MedioDePagoWsdl.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://services.soap.com/", className = "wsdlBanca.MedioDePagoWsdl.CreateResponse")
    @Action(input = "http://services.soap.com/MedioDePagoService/createRequest", output = "http://services.soap.com/MedioDePagoService/createResponse")
    public String create(
        @WebParam(name = "medioDePago", targetNamespace = "")
        MedioDePago medioDePago);

    /**
     * 
     * @return
     *     returns java.util.List<wsdlBanca.MedioDePagoWsdl.CuentaBancaria>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://services.soap.com/", className = "wsdlBanca.MedioDePagoWsdl.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://services.soap.com/", className = "wsdlBanca.MedioDePagoWsdl.FindAllResponse")
    @Action(input = "http://services.soap.com/MedioDePagoService/findAllRequest", output = "http://services.soap.com/MedioDePagoService/findAllResponse")
    public List<CuentaBancaria> findAll();

    /**
     * 
     * @param id
     * @return
     *     returns wsdlBanca.MedioDePagoWsdl.CuentaBancaria
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://services.soap.com/", className = "wsdlBanca.MedioDePagoWsdl.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://services.soap.com/", className = "wsdlBanca.MedioDePagoWsdl.FindByIdResponse")
    @Action(input = "http://services.soap.com/MedioDePagoService/findByIdRequest", output = "http://services.soap.com/MedioDePagoService/findByIdResponse")
    public CuentaBancaria findById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

}
