
package wsdlBanca.IndexWsWsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IndexWsService", targetNamespace = "http://config.soap.com/", wsdlLocation = "http://localhost:8080/BancaSoap/ws/IndexWs?wsdl")
public class IndexWsService
    extends Service
{

    private final static URL INDEXWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException INDEXWSSERVICE_EXCEPTION;
    private final static QName INDEXWSSERVICE_QNAME = new QName("http://config.soap.com/", "IndexWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/BancaSoap/ws/IndexWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INDEXWSSERVICE_WSDL_LOCATION = url;
        INDEXWSSERVICE_EXCEPTION = e;
    }

    public IndexWsService() {
        super(__getWsdlLocation(), INDEXWSSERVICE_QNAME);
    }

    public IndexWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INDEXWSSERVICE_QNAME, features);
    }

    public IndexWsService(URL wsdlLocation) {
        super(wsdlLocation, INDEXWSSERVICE_QNAME);
    }

    public IndexWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INDEXWSSERVICE_QNAME, features);
    }

    public IndexWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IndexWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IndexWs
     */
    @WebEndpoint(name = "IndexWsPort")
    public IndexWs getIndexWsPort() {
        return super.getPort(new QName("http://config.soap.com/", "IndexWsPort"), IndexWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IndexWs
     */
    @WebEndpoint(name = "IndexWsPort")
    public IndexWs getIndexWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://config.soap.com/", "IndexWsPort"), IndexWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INDEXWSSERVICE_EXCEPTION!= null) {
            throw INDEXWSSERVICE_EXCEPTION;
        }
        return INDEXWSSERVICE_WSDL_LOCATION;
    }

}
