
package wsdl.EnvioWsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EnvioService", targetNamespace = "http://services.soap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EnvioService {


    /**
     * 
     * @param id
     * @return
     *     returns wsdl.EnvioWsdl.Envio
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://services.soap.com/", className = "wsdl.EnvioWsdl.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://services.soap.com/", className = "wsdl.EnvioWsdl.FindByIdResponse")
    public Envio findById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://services.soap.com/", className = "wsdl.EnvioWsdl.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://services.soap.com/", className = "wsdl.EnvioWsdl.DeleteResponse")
    public String delete(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @return
     *     returns java.util.List<wsdl.EnvioWsdl.Envio>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://services.soap.com/", className = "wsdl.EnvioWsdl.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://services.soap.com/", className = "wsdl.EnvioWsdl.FindAllResponse")
    public List<Envio> findAll();

    /**
     * 
     * @param envio
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://services.soap.com/", className = "wsdl.EnvioWsdl.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://services.soap.com/", className = "wsdl.EnvioWsdl.CreateResponse")
    public String create(
        @WebParam(name = "envio", targetNamespace = "")
        Envio envio);

    /**
     * 
     * @param envio
     * @return
     *     returns wsdl.EnvioWsdl.Envio
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://services.soap.com/", className = "wsdl.EnvioWsdl.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://services.soap.com/", className = "wsdl.EnvioWsdl.UpdateResponse")
    public Envio update(
        @WebParam(name = "envio", targetNamespace = "")
        Envio envio);

}
