
package wsdlBanca.CuentaBancariaWsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CuentaBancariaService", targetNamespace = "http://services.soap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CuentaBancariaService {


    /**
     * 
     * @param cuentaBancaria
     * @return
     *     returns wsdlBanca.CuentaBancariaWsdl.CuentaBancaria
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://services.soap.com/", className = "wsdlBanca.CuentaBancariaWsdl.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://services.soap.com/", className = "wsdlBanca.CuentaBancariaWsdl.UpdateResponse")
    @Action(input = "http://services.soap.com/CuentaBancariaService/updateRequest", output = "http://services.soap.com/CuentaBancariaService/updateResponse")
    public CuentaBancaria update(
        @WebParam(name = "cuentaBancaria", targetNamespace = "")
        CuentaBancaria cuentaBancaria);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://services.soap.com/", className = "wsdlBanca.CuentaBancariaWsdl.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://services.soap.com/", className = "wsdlBanca.CuentaBancariaWsdl.DeleteResponse")
    @Action(input = "http://services.soap.com/CuentaBancariaService/deleteRequest", output = "http://services.soap.com/CuentaBancariaService/deleteResponse")
    public String delete(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param cuentaBancaria
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://services.soap.com/", className = "wsdlBanca.CuentaBancariaWsdl.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://services.soap.com/", className = "wsdlBanca.CuentaBancariaWsdl.CreateResponse")
    @Action(input = "http://services.soap.com/CuentaBancariaService/createRequest", output = "http://services.soap.com/CuentaBancariaService/createResponse")
    public String create(
        @WebParam(name = "cuentaBancaria", targetNamespace = "")
        CuentaBancaria cuentaBancaria);

    /**
     * 
     * @return
     *     returns java.util.List<wsdlBanca.CuentaBancariaWsdl.CuentaBancaria>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://services.soap.com/", className = "wsdlBanca.CuentaBancariaWsdl.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://services.soap.com/", className = "wsdlBanca.CuentaBancariaWsdl.FindAllResponse")
    @Action(input = "http://services.soap.com/CuentaBancariaService/findAllRequest", output = "http://services.soap.com/CuentaBancariaService/findAllResponse")
    public List<CuentaBancaria> findAll();

    /**
     * 
     * @param id
     * @return
     *     returns wsdlBanca.CuentaBancariaWsdl.CuentaBancaria
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://services.soap.com/", className = "wsdlBanca.CuentaBancariaWsdl.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://services.soap.com/", className = "wsdlBanca.CuentaBancariaWsdl.FindByIdResponse")
    @Action(input = "http://services.soap.com/CuentaBancariaService/findByIdRequest", output = "http://services.soap.com/CuentaBancariaService/findByIdResponse")
    public CuentaBancaria findById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

}
