
package wsdlBanca.CuentaBancariaWsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CuentaBancariaService", targetNamespace = "http://services.soap.com/", wsdlLocation = "http://localhost:8080/BancaSoap/ws/CuentaBancariaService?wsdl")
public class CuentaBancariaService_Service
    extends Service
{

    private final static URL CUENTABANCARIASERVICE_WSDL_LOCATION;
    private final static WebServiceException CUENTABANCARIASERVICE_EXCEPTION;
    private final static QName CUENTABANCARIASERVICE_QNAME = new QName("http://services.soap.com/", "CuentaBancariaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/BancaSoap/ws/CuentaBancariaService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUENTABANCARIASERVICE_WSDL_LOCATION = url;
        CUENTABANCARIASERVICE_EXCEPTION = e;
    }

    public CuentaBancariaService_Service() {
        super(__getWsdlLocation(), CUENTABANCARIASERVICE_QNAME);
    }

    public CuentaBancariaService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUENTABANCARIASERVICE_QNAME, features);
    }

    public CuentaBancariaService_Service(URL wsdlLocation) {
        super(wsdlLocation, CUENTABANCARIASERVICE_QNAME);
    }

    public CuentaBancariaService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUENTABANCARIASERVICE_QNAME, features);
    }

    public CuentaBancariaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CuentaBancariaService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CuentaBancariaService
     */
    @WebEndpoint(name = "CuentaBancariaServicePort")
    public CuentaBancariaService getCuentaBancariaServicePort() {
        return super.getPort(new QName("http://services.soap.com/", "CuentaBancariaServicePort"), CuentaBancariaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CuentaBancariaService
     */
    @WebEndpoint(name = "CuentaBancariaServicePort")
    public CuentaBancariaService getCuentaBancariaServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.soap.com/", "CuentaBancariaServicePort"), CuentaBancariaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUENTABANCARIASERVICE_EXCEPTION!= null) {
            throw CUENTABANCARIASERVICE_EXCEPTION;
        }
        return CUENTABANCARIASERVICE_WSDL_LOCATION;
    }

}
